class TTMThermalModelBSQ;
class TTMThermalModelBQ;

Int_t BSQConstrainSQ(TTMThermalModelBSQ *model);
Int_t BSQConstrainS(TTMThermalModelBSQ *model);
Int_t BSQConstrainQ(TTMThermalModelBSQ *model);
Int_t BSQConstrainSQEN(TTMThermalModelBSQ *model, Double_t eovern);
Int_t BSQConstrainSQPercolation(TTMThermalModelBSQ *model);
Int_t BSQConstrainSPercolation(TTMThermalModelBSQ *model);
Int_t BSQConstrainSEN(TTMThermalModelBSQ *model, Double_t eovern);
Int_t BSQConstrainSQST3(TTMThermalModelBSQ *model, Double_t sovert3);
Int_t BSQConstrainSST3(TTMThermalModelBSQ *model, Double_t sovert3);
Int_t BQConstrainQ(TTMThermalModelBQ *model);
Int_t BQConstrainQEN(TTMThermalModelBQ *model, Double_t eovern);
Int_t BQConstrainQPercolation(TTMThermalModelBQ *model);
Int_t BQConstrainST3(TTMThermalModelBQ *model, Double_t SoverT3);
Int_t BQConstrainBDens(TTMThermalModelBQ *model, Double_t nb);
Int_t BQConstrainQNetBDens(TTMThermalModelBQ *model, Double_t nb);
Int_t BQConstrainQST3(TTMThermalModelBQ *model, Double_t SoverT3);
Int_t BQConstrainQBDens(TTMThermalModelBQ *model, Double_t nb);
Int_t BQConstrainEN(TTMThermalModelBQ *model, Double_t eovern);
Int_t BSQConstrainSBDens(TTMThermalModelBSQ *model, Double_t nb);
Int_t BSQConstrainSQBDens(TTMThermalModelBSQ *model, Double_t nb);
Int_t BSQConstrainSQNetBDens(TTMThermalModelBSQ *model, Double_t nb);
